name: 'Upload Released Python Package Chart to GAR'
description: 'Extracts a Python package from a release and uploads it to GAR. This is designed to be run on a release trigger.'
inputs:
  inputs:
  credentials-json:
    description: Google credentials json
    required: true
  project-id:
    description: Google cloud project id
    required: true
  package-name:
    description: Python package name
    required: true
  version:
    description: Version to publish
    required: false
    default: ${{ github.event.release.tag_name }}
  scope:
    description: Artifact registry scope
    required: false
    default: '@unsupervised'
  repository:
    description: Artifact registry repository name
    required: false
    default: python
  location:
    description: Artifact registry location
    required: false
    default: us-central1
  proto-directory:
    description: Location of package
    required: false
    default: dist/*
runs:
  using: composite
  steps:
    - id: auth
      uses: google-github-actions/auth@v0
      with:
        credentials_json: ${{ inputs.credentials-json }}
    - uses: google-github-actions/setup-gcloud@v0.3.0
      with:
        project_id: ${{ inputs.project-id }}
    - name: Install python3/Twine
      uses: actions/setup-python@v2
      with:
        python-version: '3.8.8'
      run: pip install twine
    - name: upload python package
      shell: bash
      run: |
        twine upload --repository-url https://us-central1-python.pkg.dev/unsupervised-dev-ops/{{ inputs.repository}} {{ inputs.proto-directory }}
